#!/usr/bin/env python3
"""Sync only language menus and their shared route data from published HTML.

Run after adding a translation. Each page's canonical URL and German language
link identify its translation group. Content, metadata and publication settings
are left untouched. --check reports drift without writing files.
"""
import argparse
import html
import json
import re
from pathlib import Path
from urllib.parse import urlsplit

ROOT = Path(__file__).resolve().parents[1]
LANGUAGES = [
    ('de', 'Deutsch'), ('en', 'English'), ('it', 'Italiano'),
    ('fr', 'Français'), ('nl', 'Nederlands'), ('es', 'Español'),
    ('tr', 'Türkçe'), ('pl', 'Polski'), ('ru', 'Русский'),
    ('cs', 'Čeština'), ('ja', '日本語'), ('ko', '한국어'),
    ('id', 'Bahasa Indonesia'), ('hi', 'हिंदी'), ('ar', 'العربية'),
    ('pt-PT', 'Português (Portugal)'),
]
MENU = re.compile(r'(<div class="lang-menu">)(.*?)(</div>)', re.S)
DATA = re.compile(r'  // BEGIN LANGUAGE MENU DATA\n.*?  // END LANGUAGE MENU DATA', re.S)


def normalize(path):
    return re.sub(r'/index(?:\.html)?$', '/', path).removesuffix('.html').rstrip('/') or '/'


def attributes(tag):
    return dict(re.findall(r'([\w-]+)="([^"]*)"', tag))


def route_file(route):
    path = ROOT / route.lstrip('/')
    return path / 'index.html' if route.endswith('/') else path.with_suffix('.html')


def collect():
    pages, groups = [], {}
    for path in sorted(ROOT.rglob('*.html')):
        if '.git' in path.parts:
            continue
        text = path.read_text()
        menu = MENU.search(text)
        if not menu:
            continue  # e.g. the Google ownership verification file
        language = attributes(re.search(r'<html\b[^>]*>', text)[0])['lang']
        assert language in dict(LANGUAGES), (path, language)
        german = next(attributes(a)['href'] for a in re.findall(r'<a\b[^>]*>', menu[2])
                      if attributes(a).get('hreflang') == 'de')
        error_page = path.name == '404.html'
        group = '/' if error_page else normalize(urlsplit(german).path)
        pages.append((path, text, language, group, error_page))
        if error_page:
            continue
        canonical = next(attributes(tag)['href'] for tag in re.findall(r'<link\b[^>]*>', text)
                         if attributes(tag).get('rel') == 'canonical')
        route = urlsplit(canonical).path
        assert route_file(route).resolve() == path.resolve(), (path, route)
        siblings = groups.setdefault(group, {})
        assert language not in siblings, (group, language, path)
        siblings[language] = route
    assert set(groups['/']) == set(dict(LANGUAGES)), 'Missing language homepage'
    assert all(group == siblings.get('de') for group, siblings in groups.items())
    return pages, groups


def menu_html(language, group, error_page, groups):
    lines = []
    for code, name in LANGUAGES:
        route = groups[group].get(code, groups['/'][code])
        active = ' class="active"' if code == language else ''
        if code == language and not error_page:
            active += ' aria-current="page"'
        fallback = ' data-language-home="true"' if code not in groups[group] else ''
        lines.append(
            f'        <a href="{html.escape(route, quote=True)}" hreflang="{code}"{active}{fallback}>'
            f'<span class="lang-code" dir="ltr">{code[:2].upper()}</span>'
            f'<span class="lang-name" lang="{code}" dir="{"rtl" if code == "ar" else "ltr"}">'
            f'{html.escape(name)}</span></a>')
    return '\n' + '\n'.join(lines) + '\n      '


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    pages, groups = collect()
    changes = []
    for path, text, language, group, error_page in pages:
        replacement = menu_html(language, group, error_page, groups)
        updated = MENU.sub(lambda m: m[1] + replacement + m[3], text)
        if updated != text:
            changes.append(path)
            if not args.check:
                path.write_text(updated)
    data = '  // BEGIN LANGUAGE MENU DATA\n'
    data += '  // Generated by scripts/sync-language-menus.py from existing page canonicals.\n'
    data += '  var siteLanguages = ' + json.dumps(LANGUAGES, ensure_ascii=False) + ';\n'
    data += '  var languageRoutes = {\n'
    data += ',\n'.join('    ' + json.dumps(group) + ': ' + json.dumps(
        {code: groups[group][code] for code, _ in LANGUAGES if code in groups[group]},
        ensure_ascii=False) for group in sorted(groups))
    data += '\n  };\n  // END LANGUAGE MENU DATA'
    js_path = ROOT / 'site.js'
    js = js_path.read_text()
    assert len(DATA.findall(js)) == 1, 'Expected one shared language data block'
    updated = DATA.sub(lambda m: data, js)
    if updated != js:
        changes.append(js_path)
        if not args.check:
            js_path.write_text(updated)
    print(f'{len(pages)} pages, {len(LANGUAGES)} languages, {len(groups)} page groups; '
          f'{len(changes)} files {"need syncing" if args.check else "updated"}.')
    if args.check and changes:
        raise SystemExit(1)


if __name__ == '__main__':
    main()
